"""Tests for commit message generator with routing."""

import pytest
from unittest.mock import Mock, AsyncMock, patch

from sologit.orchestration.commit_message_generator import (
    CommitMessageGenerator,
    CommitMessageRequest,
    CommitMessageResponse,
)
from sologit.orchestration.routing_policy import PolicyEngine, RoutingPolicy
from sologit.orchestration.providers import (
    ProviderType,
    ProviderConfig,
    ProviderResponse,
    ProviderAdapter,
)


class MockProviderAdapter(ProviderAdapter):
    """Mock provider for testing."""
    
    def __init__(self, config: ProviderConfig, should_fail: bool = False):
        super().__init__(config)
        self.should_fail = should_fail
        self.call_count = 0
        self.last_prompt = None
    
    async def generate(self, prompt: str, system_prompt=None, **kwargs) -> ProviderResponse:
        self.call_count += 1
        self.last_prompt = prompt
        
        if self.should_fail:
            raise Exception(f"{self.provider_type.value} failed")
        
        return ProviderResponse(
            content=f"feat: Generated by {self.provider_type.value}",
            provider=self.provider_type,
            model="mock-model",
            tokens_used=50,
            latency_ms=100.0,
            cost_usd=0.001,
        )
    
    def is_available(self) -> bool:
        return True
    
    def get_default_model(self) -> str:
        return "mock-model"


class TestCommitMessageRequest:
    """Test commit message request."""
    
    def test_basic_request(self):
        request = CommitMessageRequest(
            diff="+ some code",
            workpad_title="feature-branch"
        )
        assert request.diff == "+ some code"
        assert request.workpad_title == "feature-branch"
        assert request.conventional_commit is True
    
    def test_request_with_context(self):
        request = CommitMessageRequest(
            diff="+ fix bug",
            workpad_title="bugfix",
            test_results="All tests passed",
            context="Fixed null pointer",
            conventional_commit=False
        )
        assert request.test_results == "All tests passed"
        assert request.context == "Fixed null pointer"
        assert request.conventional_commit is False


class TestCommitMessageGenerator:
    """Test commit message generation with routing."""
    
    @pytest.mark.asyncio
    async def test_generate_with_primary_success(self):
        # Setup
        adapters = {
            ProviderType.ABACUS: MockProviderAdapter(
                ProviderConfig(provider_type=ProviderType.ABACUS, api_key="key1")
            ),
            ProviderType.OPENAI: MockProviderAdapter(
                ProviderConfig(provider_type=ProviderType.OPENAI, api_key="key2")
            ),
        }
        policy = RoutingPolicy()
        engine = PolicyEngine(policy, adapters)
        generator = CommitMessageGenerator(engine)
        
        request = CommitMessageRequest(
            diff="+ added feature",
            workpad_title="new-feature"
        )
        
        # Test
        response = await generator.generate(request)
        
        # Assert
        assert "feat: Generated by abacus" in response.message
        assert response.provider == ProviderType.ABACUS
        assert response.fallback_used is False
        assert adapters[ProviderType.ABACUS].call_count == 1
        assert adapters[ProviderType.OPENAI].call_count == 0
    
    @pytest.mark.asyncio
    async def test_generate_with_fallback(self):
        # Setup - primary fails, fallback succeeds
        adapters = {
            ProviderType.ABACUS: MockProviderAdapter(
                ProviderConfig(provider_type=ProviderType.ABACUS, api_key="key1"),
                should_fail=True
            ),
            ProviderType.OPENAI: MockProviderAdapter(
                ProviderConfig(provider_type=ProviderType.OPENAI, api_key="key2"),
                should_fail=False
            ),
        }
        policy = RoutingPolicy()
        engine = PolicyEngine(policy, adapters)
        generator = CommitMessageGenerator(engine)
        
        request = CommitMessageRequest(
            diff="+ fixed bug",
            workpad_title="bugfix"
        )
        
        # Test
        response = await generator.generate(request)
        
        # Assert
        assert "feat: Generated by openai" in response.message
        assert response.provider == ProviderType.OPENAI
        assert response.fallback_used is True
        assert adapters[ProviderType.ABACUS].call_count == 1
        assert adapters[ProviderType.OPENAI].call_count == 1
    
    @pytest.mark.asyncio
    async def test_generate_all_providers_fail(self):
        # Setup - all providers fail
        adapters = {
            ProviderType.ABACUS: MockProviderAdapter(
                ProviderConfig(provider_type=ProviderType.ABACUS, api_key="key1"),
                should_fail=True
            ),
            ProviderType.OPENAI: MockProviderAdapter(
                ProviderConfig(provider_type=ProviderType.OPENAI, api_key="key2"),
                should_fail=True
            ),
        }
        policy = RoutingPolicy()
        engine = PolicyEngine(policy, adapters)
        generator = CommitMessageGenerator(engine)
        
        request = CommitMessageRequest(
            diff="+ changes",
            workpad_title="test"
        )
        
        # Test - should raise error
        with pytest.raises(RuntimeError, match="All AI providers failed"):
            await generator.generate(request)
    
    @pytest.mark.asyncio
    async def test_build_prompt_conventional(self):
        # Setup
        adapters = {
            ProviderType.ABACUS: MockProviderAdapter(
                ProviderConfig(provider_type=ProviderType.ABACUS, api_key="key1")
            ),
        }
        policy = RoutingPolicy()
        engine = PolicyEngine(policy, adapters)
        generator = CommitMessageGenerator(engine)
        
        request = CommitMessageRequest(
            diff="+ added file.py",
            workpad_title="feature-x",
            conventional_commit=True
        )
        
        # Test
        await generator.generate(request)
        
        # Assert - check that prompt was built correctly
        prompt = adapters[ProviderType.ABACUS].last_prompt
        assert "Workpad: feature-x" in prompt
        assert "+ added file.py" in prompt
        assert "Conventional Commits" in prompt
    
    @pytest.mark.asyncio
    async def test_build_prompt_with_context(self):
        # Setup
        adapters = {
            ProviderType.ABACUS: MockProviderAdapter(
                ProviderConfig(provider_type=ProviderType.ABACUS, api_key="key1")
            ),
        }
        policy = RoutingPolicy()
        engine = PolicyEngine(policy, adapters)
        generator = CommitMessageGenerator(engine)
        
        request = CommitMessageRequest(
            diff="+ fix",
            workpad_title="bugfix",
            test_results="3 tests passed",
            context="Fixed memory leak"
        )
        
        # Test
        await generator.generate(request)
        
        # Assert
        prompt = adapters[ProviderType.ABACUS].last_prompt
        assert "Test Results: 3 tests passed" in prompt
        assert "Context: Fixed memory leak" in prompt
    
    def test_build_system_prompt_conventional(self):
        # Setup
        adapters = {}
        policy = RoutingPolicy()
        engine = PolicyEngine(policy, adapters)
        generator = CommitMessageGenerator(engine)
        
        request = CommitMessageRequest(
            diff="test",
            workpad_title="test",
            conventional_commit=True
        )
        
        # Test
        system_prompt = generator._build_system_prompt(request)
        
        # Assert
        assert "feat:" in system_prompt
        assert "fix:" in system_prompt
        assert "refactor:" in system_prompt
        assert "72 characters" in system_prompt
    
    def test_build_system_prompt_free_form(self):
        # Setup
        adapters = {}
        policy = RoutingPolicy()
        engine = PolicyEngine(policy, adapters)
        generator = CommitMessageGenerator(engine)
        
        request = CommitMessageRequest(
            diff="test",
            workpad_title="test",
            conventional_commit=False
        )
        
        # Test
        system_prompt = generator._build_system_prompt(request)
        
        # Assert
        assert "72 characters" in system_prompt
        assert "WHAT changed and WHY" in system_prompt
        assert "feat:" not in system_prompt


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
