
"""
Configuration templates and examples for Solo Git.
"""

# Default configuration template
DEFAULT_CONFIG_TEMPLATE = """# Solo Git Configuration
# Generated by evogitctl config setup

# Abacus.ai API Configuration
# All AI operations use this cloud API - no local model hosting needed!
# Note: Abacus.ai uses a deployment-based model. See docs for setup.
abacus:
  endpoint: https://api.abacus.ai/api/v0
  api_key: YOUR_API_KEY_HERE  # Service key (s2_...) from https://abacus.ai

# Model Selection Strategy
# Solo Git automatically selects the best model for each task
ai:
  models:
    # Planning models - complex reasoning and architecture decisions
    planning:
      primary:
        name: gpt-4o
        provider: openai
        max_tokens: 4096
        temperature: 0.2
        cost_per_1k_tokens: 0.0300
      fallback:
        name: claude-3-5-sonnet
        provider: anthropic
        max_tokens: 4096
        temperature: 0.2
        cost_per_1k_tokens: 0.0250

    # Coding models - specialized code generation
    coding:
      primary:
        name: deepseek-coder-33b
        provider: abacus
        max_tokens: 2048
        temperature: 0.1
        cost_per_1k_tokens: 0.0005
      fallback:
        name: codellama-70b-instruct
        provider: abacus
        max_tokens: 2048
        temperature: 0.1
        cost_per_1k_tokens: 0.0005

    # Fast models - quick iterations and linting
    fast:
      primary:
        name: llama-3.1-8b-instruct
        provider: abacus
        max_tokens: 1024
        temperature: 0.1
        cost_per_1k_tokens: 0.0001
      fallback:
        name: gemma-2-9b-it
        provider: abacus
        max_tokens: 1024
        temperature: 0.1
        cost_per_1k_tokens: 0.0001

# Budget Controls
budget:
  daily_usd_cap: 10.0          # Maximum daily spend
  alert_threshold: 0.8          # Alert at 80% of cap
  track_by_model: true          # Track costs per model
  
  # Escalation triggers - when to use smarter (more expensive) models
  escalation_triggers:
    patch_lines: 200                                          # Large changes
    test_failures: 2                                          # Repeated failures
    security_keywords: [auth, crypto, password, token, jwt]   # Security-sensitive
    complexity_score: 0.7                                     # Complex code

# Test Configuration
tests:
  timeout_seconds: 300
  parallel_max: 4
  
  # Fast tests (run before auto-merge)
  fast_tests:
    - name: unit-tests
      cmd: pytest tests/unit -q
      timeout: 30
  
  # Full tests (run in CI after merge)
  full_tests:
    - name: integration
      cmd: pytest tests/integration
      timeout: 120

# Repository Settings
repos_path: ~/.sologit/repos
workpad_ttl_days: 7

# Solo Git Workflow
promote_on_green: true    # Auto-merge when tests pass
rollback_on_ci_red: true  # Auto-rollback if CI fails
"""


# Environment variables template
ENV_TEMPLATE = """# Solo Git Environment Variables
# Copy this to .env and fill in your values

# Abacus.ai API (Required)
ABACUS_API_ENDPOINT=https://api.abacus.ai/api/v0
ABACUS_API_KEY=your-api-key-here  # Service key (s2_...)

# Budget Controls
DAILY_USD_CAP=10.0

# Optional: Custom repos location
# SOLOGIT_REPOS_PATH=/custom/path/to/repos

# Optional: Logging
# SOLOGIT_LOG_LEVEL=INFO
"""

