
"""
Configuration templates and examples for Solo Git.
"""

# Default configuration template
DEFAULT_CONFIG_TEMPLATE = """# Solo Git Configuration
# Generated by evogitctl config setup

# Abacus.ai API Configuration
# All AI operations use this cloud API - no local model hosting needed!
# Note: Abacus.ai uses a deployment-based model. See docs for setup.
abacus:
  endpoint: https://api.abacus.ai/api/v0
  api_key: YOUR_API_KEY_HERE  # Service key (s2_...) from https://abacus.ai

# Model Selection Strategy
# Solo Git automatically selects the best model for each task
models:
  # Planning models - for complex reasoning and architecture decisions
  planning_model: gpt-4o
  planning_fallback: claude-3-5-sonnet
  planning_max_tokens: 4096
  planning_temperature: 0.2
  
  # Coding models - for specialized code generation
  coding_model: deepseek-coder-33b
  coding_fallback: codellama-70b-instruct
  coding_max_tokens: 2048
  coding_temperature: 0.1
  
  # Fast models - for quick operations
  fast_model: llama-3.1-8b-instruct
  fast_fallback: gemma-2-9b-it
  fast_max_tokens: 1024
  fast_temperature: 0.1

# Budget Controls
budget:
  daily_usd_cap: 10.0          # Maximum daily spend
  alert_threshold: 0.8          # Alert at 80% of cap
  track_by_model: true          # Track costs per model
  
  # Escalation triggers - when to use smarter (more expensive) models
  escalation_triggers:
    patch_lines: 200                                          # Large changes
    test_failures: 2                                          # Repeated failures
    security_keywords: [auth, crypto, password, token, jwt]   # Security-sensitive
    complexity_score: 0.7                                     # Complex code

# Test Configuration
tests:
  sandbox_image: ghcr.io/solo-git/sandbox:latest
  timeout_seconds: 300
  parallel_max: 4
  
  # Fast tests (run before auto-merge)
  fast_tests:
    - name: unit-tests
      cmd: pytest tests/unit -q
      timeout: 30
  
  # Full tests (run in CI after merge)
  full_tests:
    - name: integration
      cmd: pytest tests/integration
      timeout: 120

# Repository Settings
repos_path: ~/.sologit/repos
workpad_ttl_days: 7

# Solo Git Workflow
promote_on_green: true    # Auto-merge when tests pass
rollback_on_ci_red: true  # Auto-rollback if CI fails
"""


# Environment variables template
ENV_TEMPLATE = """# Solo Git Environment Variables
# Copy this to .env and fill in your values

# Abacus.ai API (Required)
ABACUS_API_ENDPOINT=https://api.abacus.ai/api/v0
ABACUS_API_KEY=your-api-key-here  # Service key (s2_...)

# Budget Controls
DAILY_USD_CAP=10.0

# Optional: Custom repos location
# SOLOGIT_REPOS_PATH=/custom/path/to/repos

# Optional: Logging
# SOLOGIT_LOG_LEVEL=INFO
"""

